#!/usr/bin/env python3
"""
GeckoBot Poker - Log Analysis Tool
Run this script to analyze the logs generated by the poker bot.
"""

import os
import sys
from log_analyzer import LogAnalyzer

def main():
    """Main function to run the log analyzer"""
    # Create logs directory if it doesn't exist
    if not os.path.exists('logs'):
        print("No logs directory found. Please run the poker bot first.")
        sys.exit(1)
        
    # Check if any log files exist
    data_files = [f for f in os.listdir('logs') if f.endswith('_data.json')]
    if not data_files:
        print("No log data files found. Please run the poker bot first.")
        sys.exit(1)
    
    # Create analyzer with most recent session
    analyzer = LogAnalyzer()
    
    # List available sessions
    print("\nAvailable sessions:")
    sessions = analyzer.list_available_sessions()
    print(sessions)
    
    # Generate report for the most recent session
    print("\nGenerating report for the most recent session...")
    report_path = analyzer.generate_report()
    print(f"Report generated: {report_path}")
    
    # Open the report in the default browser
    try:
        import webbrowser
        webbrowser.open(f"file://{os.path.abspath(report_path)}")
        print("Report opened in browser")
    except:
        print(f"Please open the report manually: {report_path}")
    
if __name__ == "__main__":
    main()
